# Generated by Django 3.0.2 on 2020-01-19 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import regex_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAnswerLinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BotQuestionRegexModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', regex_field.fields.RegexField(max_length=500)),
                ('answer_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.BotAnswerLinkModel')),
            ],
        ),
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='botanswerlinkmodel',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.BotModel'),
        ),
    ]
