# Generated by Django 3.0.2 on 2020-01-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botquestionregexmodel',
            old_name='word',
            new_name='regex',
        ),
    ]
