# Generated by Django 3.0.2 on 2020-01-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200119_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botquestionregexmodel',
            name='regex',
        ),
    ]
