# Generated by Django 3.0.2 on 2020-01-19 13:45

from django.db import migrations
import regex_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_botquestionregexmodel_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='botquestionregexmodel',
            name='regex',
            field=regex_field.fields.RegexField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
