# Generated by Django 2.1 on 2020-01-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botquestionregexmodel_regex'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAnswerTextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.BotModel')),
            ],
        ),
        migrations.CreateModel(
            name='ChatTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1000)),
            ],
        ),
    ]
