# Generated by Django 2.1 on 2020-01-19 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_botanswertextmodel_chattransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botquestionregexmodel',
            name='answer_link',
        ),
        migrations.AddField(
            model_name='botquestionregexmodel',
            name='answer',
            field=models.CharField(choices=[('LINK', 'Link'), ('TEXT', 'Text')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botquestionregexmodel',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.BotAnswerLinkModel'),
        ),
        migrations.AddField(
            model_name='botquestionregexmodel',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.BotAnswerTextModel'),
        ),
    ]
