# Generated by Django 2.1 on 2020-01-19 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20200119_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatTransaction',
            new_name='ChatTransactionModel',
        ),
        migrations.AlterField(
            model_name='botquestionregexmodel',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.BotAnswerLinkModel'),
        ),
        migrations.AlterField(
            model_name='botquestionregexmodel',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.BotAnswerTextModel'),
        ),
    ]
