# Generated by Django 2.1 on 2020-01-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20200119_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattransactionmodel',
            name='response',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
